"""Pure functions that produce Godot 4.x project file content.

Uses the advanced implementations with game_type-aware input maps and
smart entity positioning from the original AI orchestrator.
"""
from __future__ import annotations

import re
from typing import Any
from uuid import uuid4


def _safe_filename(name: str) -> str:
    """Convert entity name to a safe lowercase filename slug."""
    slug = name.lower().replace(" ", "_").replace("-", "_")
    slug = re.sub(r"[^a-z0-9_]", "", slug)
    slug = re.sub(r"_+", "_", slug).strip("_")
    return slug or "entity"


def _safe_node_name(name: str) -> str:
    """Convert entity name to a valid Godot node name (PascalCase, no special chars)."""
    cleaned = re.sub(r"[^a-zA-Z0-9 ]", "", name)
    return cleaned.replace(" ", "") or "Entity"


def _generate_project_config(game_name: str, game_type: str = "arcade") -> str:
    """Return a valid Godot 4.2 project.godot configuration string."""

    # Add additional input maps for specific game types
    extra_inputs = ""
    if game_type in ("racing", "topdown", "snake", "survival"):
        extra_inputs = """
move_up={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194320,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
move_down={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":83,"key_label":0,"unicode":115,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194322,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
shoot={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":90,"key_label":0,"unicode":122,"location":0,"echo":false,"script":null)]
}}"""
    elif game_type in ("shooter", "space_shooter"):
        extra_inputs = """
move_up={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194320,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
move_down={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":83,"key_label":0,"unicode":115,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194322,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
shoot={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":32,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":90,"key_label":0,"unicode":122,"location":0,"echo":false,"script":null)]
}}"""

    return f"""; Engine configuration file.
; Generated by AI Game Dev IDE.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="{game_name}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.2", "Forward Plus")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[input]

move_right={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":100,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194321,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
move_left={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":97,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194319,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
jump={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":32,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"location":0,"echo":false,"script":null)]
}}{extra_inputs}

[layer_names]

2d_physics/layer_1="Player"
2d_physics/layer_2="Enemies"
2d_physics/layer_3="World"
2d_physics/layer_4="Collectibles"

[rendering]

textures/canvas_textures/default_texture_filter=0
"""


def _generate_main_scene(entities: list[dict[str, Any]], game_type: str = "arcade") -> str:
    """Return a minimal main.tscn that provides a ground and instances entities."""
    uid = uuid4().hex[:8]
    shape_id = f"RectangleShape2D_{uid}"
    load_steps = 1 + len(entities)

    ext_res_lines = []
    for i, entity in enumerate(entities):
        fname = _safe_filename(entity.get("name", f"Entity{i}"))
        ext_res_lines.append(
            f'[ext_resource type="PackedScene" path="res://scenes/{fname}.tscn" id="{i + 1}"]'
        )

    # Position entities based on their type for better layout
    instance_lines = []
    for i, entity in enumerate(entities):
        node_name = _safe_node_name(entity.get("name", f"Entity{i}"))
        etype = entity.get("type", "character").lower()

        # Smart positioning based on entity type and game type
        if etype in ("ui", "display"):
            x_pos, y_pos = 640, 40  # Top center for UI
        elif etype in ("environment", "background"):
            x_pos, y_pos = 640, 360  # Center for backgrounds
        elif etype in ("character", "player", "vehicle"):
            if game_type == "flappy":
                x_pos, y_pos = 120, 300  # Left side for flappy bird
            elif game_type == "racing":
                x_pos, y_pos = 640, 500  # Bottom center for racing
            else:
                x_pos, y_pos = 200, 500  # Left area for player
        elif etype in ("enemy", "boss"):
            x_pos, y_pos = 800 + i * 100, 500  # Right side for enemies
        elif etype in ("obstacle",):
            x_pos, y_pos = 400 + i * 150, 400  # Mid area for obstacles
        elif etype in ("collectible", "trigger"):
            x_pos, y_pos = 300 + i * 120, 350  # Scattered for collectibles
        elif etype in ("projectile",):
            x_pos, y_pos = 0, -100  # Off-screen for projectile templates
        else:
            x_pos, y_pos = 100 + i * 200, 500

        instance_lines.append(
            f'[node name="{node_name}" parent="." instance=ExtResource("{i + 1}")]\n'
            f"position = Vector2({x_pos}, {y_pos})"
        )

    ext_res_block = "\n".join(ext_res_lines)
    instance_block = "\n\n".join(instance_lines)

    return f"""[gd_scene load_steps={load_steps} format=3 uid="uid://{uid}"]

{ext_res_block}

[sub_resource type="RectangleShape2D" id="{shape_id}"]
size = Vector2(1280, 32)

[node name="Main" type="Node2D"]

[node name="Ground" type="StaticBody2D" parent="."]
position = Vector2(640, 700)

[node name="CollisionShape2D" type="CollisionShape2D" parent="Ground"]
shape = SubResource("{shape_id}")

{instance_block}
"""


def _generate_icon_svg() -> str:
    return """<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64">
  <rect width="64" height="64" rx="8" fill="#4A90E2"/>
  <text x="32" y="44" font-size="32" text-anchor="middle" fill="#fff">G</text>
</svg>
"""


def _generate_readme(game_type: str, mechanics: list[str]) -> str:
    mech_str = ", ".join(mechanics) if mechanics else "standard"
    return f"""
Auto-generated Godot 4.x project by AI Game Dev IDE.

## Details
- **Type:** {game_type}
- **Mechanics:** {mech_str}

## How to Run
1. Open this folder in Godot 4.2 or later
2. Press **F5** to play

## Controls
- **Arrow keys / WASD** — move
- **Space / W** — jump

## Structure
```
scenes/     — .tscn scene files
scripts/    — GDScript (.gd) files
assets/     — Sprites and textures
```

*Generated by AI Game Dev IDE*
"""
