"""AI orchestration with provider adapters and deterministic fallback."""
from __future__ import annotations

import asyncio
import base64
import json
import logging
import uuid
from uuid import uuid4
from dataclasses import dataclass, field
from typing import Any

from app.agents.asset_agent import asset_agent
from app.agents.scene_agent import scene_agent
from app.agents.script_agent import _fallback_for as _fallback_script, script_agent
from app.services.ai_providers import ProviderUsage, provider_manager
from app.services.s3_storage import s3_storage

logger = logging.getLogger(__name__)


@dataclass
class GodotGenerateResult:
    design_doc: dict[str, Any] = field(default_factory=dict)
    file_urls: list[dict[str, str]] = field(default_factory=list)
    stats: dict[str, int] = field(default_factory=dict)
    status: str = ""
    errors: list[str] = field(default_factory=list)


@dataclass
class OrchestratorResult:
    summary: str = ""
    payload: dict[str, Any] = field(default_factory=dict)
    usage: ProviderUsage = field(default_factory=ProviderUsage)


async def _emit(realtime: Any, project_id: str, event: str, payload: Any = None) -> None:
    """Broadcast a WebSocket event; silently no-ops if realtime is None."""
    if realtime is None:
        return
    try:
        await realtime.broadcast(project_id, event, payload)
    except Exception:
        pass


def _normalize_entity(entity: Any) -> dict[str, Any]:
    """Coerce a string or partial dict entity entry to a full descriptor."""
    if isinstance(entity, dict):
        return {
            "name": entity.get("name", "Entity").strip().title(),
            "type": entity.get("type", "character"),
            "behaviors": entity.get("behaviors", entity.get("components", ["movement", "jumping"])),
        }
    name = str(entity).strip().title()
    lower = name.lower()
    if any(k in lower for k in ("patrol", "enemy", "boss")):
        etype = "enemy"
        behaviors = ["patrol"]
    elif any(k in lower for k in ("coin", "collect", "collectible")):
        etype = "collectible"
        behaviors = ["idle"]
    else:
        etype = "character"
        behaviors = ["movement", "jumping"]
    return {"name": name, "type": etype, "behaviors": behaviors}


def _generate_project_config(game_name: str) -> str:
    """Return a valid Godot 4.2 project.godot configuration string."""
    return f"""; Engine configuration file.
; Generated by AI Game Dev IDE.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="{game_name}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.2", "Forward Plus")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[input]

move_right={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":100,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194321,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
move_left={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":97,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194319,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}
jump={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":32,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"location":0,"echo":false,"script":null)]
}}

[layer_names]

2d_physics/layer_1="Player"
2d_physics/layer_2="Enemies"
2d_physics/layer_3="World"
2d_physics/layer_4="Collectibles"

[rendering]

textures/canvas_textures/default_texture_filter=0
"""


def _generate_main_scene(entities: list[dict[str, Any]]) -> str:
    """Return a minimal main.tscn that provides a ground and instances entities."""
    uid = uuid4().hex[:8]
    shape_id = f"RectangleShape2D_{uid}"
    load_steps = 1 + len(entities)

    ext_res_lines = []
    for i, entity in enumerate(entities):
        name = entity.get("name", f"Entity{i}").lower().replace(" ", "_")
        ext_res_lines.append(
            f'[ext_resource type="PackedScene" path="res://scenes/{name}.tscn" id="{i + 1}"]'
        )

    instance_lines = []
    for i, entity in enumerate(entities):
        ename = entity.get("name", f"Entity{i}")
        x_pos = 100 + i * 200
        instance_lines.append(
            f'[node name="{ename}" parent="." instance=ExtResource("{i + 1}")]\n'
            f"position = Vector2({x_pos}, 600)"
        )

    ext_res_block = "\n".join(ext_res_lines)
    instance_block = "\n\n".join(instance_lines)

    return f"""[gd_scene load_steps={load_steps} format=3 uid="uid://{uid}"]

{ext_res_block}

[sub_resource type="RectangleShape2D" id="{shape_id}"]
size = Vector2(1280, 32)

[node name="Main" type="Node2D"]

[node name="Ground" type="StaticBody2D" parent="."]
position = Vector2(640, 700)

[node name="CollisionShape2D" type="CollisionShape2D" parent="Ground"]
shape = SubResource("{shape_id}")

{instance_block}
"""


def _generate_icon_svg() -> str:
    return """<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64">
  <rect width="64" height="64" rx="8" fill="#4A90E2"/>
  <text x="32" y="44" font-size="32" text-anchor="middle" fill="#fff">G</text>
</svg>
"""


def _generate_readme(game_type: str, mechanics: list[str]) -> str:
    mech_str = ", ".join(mechanics) if mechanics else "standard"
    return f"""
Auto-generated Godot 4.x project by AI Game Dev IDE.

## Details
- **Type:** {game_type}
- **Mechanics:** {mech_str}

## How to Run
1. Open this folder in Godot 4.2 or later
2. Press **F5** to play

## Controls
- **Arrow keys / WASD** — move
- **Space / W** — jump

## Structure
```
scenes/     — .tscn scene files
scripts/    — GDScript (.gd) files
assets/     — Sprites and textures
```

*Generated by AI Game Dev IDE*
"""


class AIOrchestrator:
    def _infer_game_type(self, prompt: str) -> str:
        lower = prompt.lower()
        if any(k in lower for k in ("platform", "platformer")):
            return "platformer"
        if any(k in lower for k in ("shoot", "shooter")):
            return "shooter"
        if "racing" in lower:
            return "racing"
        if "puzzle" in lower:
            return "puzzle"
        return "arcade"

    def _infer_entities(self, prompt: str) -> list[str]:
        entities = ["Player"]
        lower = prompt.lower()
        if any(k in lower for k in ("enemy", "enemies", "monster")):
            entities.append("Enemy")
        if any(k in lower for k in ("coin", "collect", "collectible")):
            entities.append("Coin")
        if any(k in lower for k in ("boss", "knight")):
            entities.append("Boss")
        return list(sorted(set(entities)))

    def _extract_json_object(self, text: str) -> dict[str, Any]:
        text = text.strip()
        if text.startswith("```"):
            lines = [l for l in text.splitlines() if not l.startswith("```")]
            text = "\n".join(lines).strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1:
            try:
                return json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                pass
        return {}

    def _fallback_design(self, prompt: str) -> dict[str, Any]:
        game_type = self._infer_game_type(prompt)
        entities = self._infer_entities(prompt)
        mechanics = ["jump", "gravity", "collect", "collectibles"]
        return {
            "summary": f"Generated {game_type} game using deterministic fallback.",
            "game_type": game_type,
            "mechanics": mechanics,
            "entities": entities,
            "win_conditions": ["Reach target score", "Survive until level complete"],
            "technical_requirements": {"framework": "phaser", "width": 800, "height": 600},
        }

    def _fallback_code(self, prompt: str) -> dict[str, Any]:
        game_type = self._infer_game_type(prompt)
        html = self._self_contained_html_game(game_type)
        return {
            "summary": "Generated starter HTML game using deterministic fallback.",
            "files": {"index.html": html},
            "entry_point": "index.html",
            "dependencies": [],
        }

    def _self_contained_html_game(self, game_type: str) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HTML Game</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ background: #111; display: flex; justify-content: center; align-items: center;
           min-height: 100vh; font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', 'Segoe UI', Helvetica, Arial, sans-serif;
           -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; }}
    canvas {{ border: 1px solid #333; border-radius: 4px; }}
    #ui {{ position: absolute; top: 16px; left: 16px; color: #eee; font-size: 14px; }}
  </style>
</head>
<body>
  <div id="ui"><span id="score">Score: 0</span></div>
  <canvas id="game" width="800" height="500"></canvas>
  <script>
    const canvas = document.getElementById('game');
    const ctx = canvas.getContext('2d');
    let score = 0;
    const player = {{ x: 100, y: 400, w: 30, h: 30, vy: 0, speed: 4, grounded: true }};
    const keys = {{}};
    const coins = Array.from({{length: 8}}, (_, i) => ({{
      x: 120 + i * 85, y: 250 + Math.random() * 150, r: 8, alive: true
    }}));
    const platforms = [
      {{ x: 0, y: 470, w: 800, h: 30 }},
      {{ x: 150, y: 370, w: 120, h: 14 }},
      {{ x: 350, y: 310, w: 140, h: 14 }},
      {{ x: 550, y: 250, w: 120, h: 14 }},
    ];
    document.addEventListener('keydown', e => keys[e.key] = true);
    document.addEventListener('keyup', e => keys[e.key] = false);
    function update() {{
      if (keys['ArrowLeft'] || keys['a']) player.x -= player.speed;
      if (keys['ArrowRight'] || keys['d']) player.x += player.speed;
      if ((keys['ArrowUp'] || keys['w'] || keys[' ']) && player.grounded) {{
        player.vy = -10; player.grounded = false;
      }}
      player.vy += 0.5; player.y += player.vy;
      player.grounded = false;
      platforms.forEach(p => {{
        if (player.x + player.w > p.x && player.x < p.x + p.w &&
            player.y + player.h >= p.y && player.y + player.h <= p.y + p.h + 8 && player.vy >= 0) {{
          player.y = p.y - player.h; player.vy = 0; player.grounded = true;
        }}
      }});
      if (player.x < 0) player.x = 0;
      if (player.x + player.w > canvas.width) player.x = canvas.width - player.w;
      coins.forEach(c => {{
        if (!c.alive) return;
        const dx = (player.x + player.w/2) - c.x, dy = (player.y + player.h/2) - c.y;
        if (Math.sqrt(dx*dx + dy*dy) < c.r + 15) {{
          c.alive = false; score++;
          document.getElementById('score').textContent = 'Score: ' + score;
        }}
      }});
    }}
    function draw() {{
      ctx.fillStyle = '#111'; ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = '#444';
      platforms.forEach(p => ctx.fillRect(p.x, p.y, p.w, p.h));
      ctx.fillStyle = '#5b9aff';
      ctx.fillRect(player.x, player.y, player.w, player.h);
      ctx.fillStyle = '#fbbf24';
      coins.forEach(c => {{
        if (!c.alive) return;
        ctx.beginPath(); ctx.arc(c.x, c.y, c.r, 0, Math.PI * 2); ctx.fill();
      }});
      ctx.fillStyle = '#888'; ctx.font = '12px system-ui';
      ctx.fillText('Type: {game_type} | Arrow keys / WASD to move', 10, canvas.height - 10);
    }}
    function loop() {{ update(); draw(); requestAnimationFrame(loop); }}
    loop();
  </script>
</body>
</html>"""

    def _format_history(self, history: list[dict]) -> str:
        if not history:
            return ""
        lines = ["\nPREVIOUS CONVERSATION HISTORY:"]
        for msg in history:
            role = msg.get("role", "unknown")
            content = msg.get("content", "")
            lines.append(f"{role.upper()}: {content}")
        lines.append("END HISTORY\n")
        return "\n".join(lines)

    async def generate_design(
        self,
        prompt: str,
        history: list[dict] | None = None,
    ) -> OrchestratorResult:
        system = (
            "You are an expert game design architect. Analyze the request and return a "
            "COMPLETE Game Design Document as strict JSON. Do not include markdown formatting "
            "like ```json ... ``` or any text outside the JSON. The JSON must strictly follow "
            'this schema:\n{\n  "summary": "Brief overview of the game",\n'
            '  "game_type": "One of: platformer, shooter, rpg, puzzle, arcade, racing",\n'
            '  "mechanics": ["List of core mechanics"],\n'
            '  "entities": ["List of game entities"],\n'
            '  "win_conditions": ["List of win conditions"],\n'
            '  "technical_requirements": {"framework": "phaser", "width": 800, "height": 600}\n}'
        )
        history_text = self._format_history(history or [])
        full_prompt = f"{system}{history_text}\nCURRENT REQUEST: {prompt}"

        try:
            result = await provider_manager.generate(full_prompt, temperature=0.7)
            design = self._extract_json_object(result.text)
            if not design:
                design = self._fallback_design(prompt)
            summary = design.get("summary", "Generated game design.")
            return OrchestratorResult(summary=summary, payload=design, usage=result.usage)
        except Exception:
            design = self._fallback_design(prompt)
            return OrchestratorResult(
                summary=design["summary"],
                payload=design,
                usage=ProviderUsage(),
            )

    async def generate_code(
        self,
        prompt: str,
        design_doc: dict[str, Any] | None = None,
        history: list[dict] | None = None,
    ) -> OrchestratorResult:
        system = (
            "You are an expert HTML5 game developer. Generate a COMPLETE, SELF-CONTAINED, "
            "PLAYABLE HTML game in a SINGLE index.html file. The game MUST:\n"
            "1. Be a single HTML file with ALL CSS in a <style> tag and ALL JavaScript in a <script> tag.\n"
            "2. Use HTML5 Canvas for rendering.\n"
            "3. Have actual game logic — player movement, collision, scoring, win/lose conditions.\n"
            "4. Have a dark background (#111 or similar) and look polished.\n"
            "5. Be immediately playable with keyboard controls.\n"
            "6. NOT depend on any external libraries, CDNs, or assets.\n"
            "7. Use this exact font stack everywhere: font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Inter', 'Segoe UI', Helvetica, Arial, sans-serif;\n"
            "8. Add -webkit-font-smoothing: antialiased; and -moz-osx-font-smoothing: grayscale; to the body element.\n"
            "9. Use font-weight: 300-600 for a clean Apple-like appearance. Use letter-spacing: -0.01em to -0.03em for headings.\n\n"
            "Return ONLY valid strict JSON. Do not include markdown formatting like ```json.\n"
            "The JSON must follow this exact structure:\n"
            '{\n  "summary": "Brief description of the game",\n'
            '  "files": {\n    "index.html": "The complete self-contained HTML game code"\n  },\n'
            '  "entry_point": "index.html",\n  "dependencies": []\n}\n\n'
            "CRITICAL RULES:\n"
            "- The 'files' object MUST have exactly one key: 'index.html'\n"
            "- The value must be the FULL HTML document string (<!DOCTYPE html> ... </html>)\n"
            "- NO placeholders, NO external dependencies, NO CDN links\n"
            "- The game must WORK when opened in a browser\n"
            "- Use requestAnimationFrame for the game loop\n"
            "- Include instructions in the game UI showing controls"
        )

        history_text = self._format_history(history or [])
        design_text = f"\nDesign document:\n{json.dumps(design_doc)}\n" if design_doc else ""
        full_prompt = f"{system}{design_text}{history_text}\nCURRENT REQUEST: {prompt}"

        try:
            result = await provider_manager.generate(full_prompt, temperature=0.5)
            code_doc = self._extract_json_object(result.text)
            if not code_doc or "files" not in code_doc:
                code_doc = self._fallback_code(prompt)
            summary = code_doc.get("summary", "Generated HTML game.")
            return OrchestratorResult(summary=summary, payload=code_doc, usage=result.usage)
        except Exception:
            code_doc = self._fallback_code(prompt)
            return OrchestratorResult(
                summary=code_doc["summary"],
                payload=code_doc,
                usage=ProviderUsage(),
            )

    async def generate_complete_game(
        self,
        prompt: str,
        username: str,
        project_name: str,
        project_id: str,
        realtime: Any = None,
    ) -> GodotGenerateResult:
        """Orchestrate all agents to produce a complete Godot 4.x project.

        Phases:
          1. Design   — DesignAgent produces game_type, entities, mechanics
          2. Assets   — AssetAgent generates sprites in parallel + tileset + bg
          3. Scripts  — ScriptAgent generates .gd files in parallel
          4. Scenes   — SceneAgent generates .tscn files in parallel
          5. Assembly — main.tscn, project.godot, icon.svg, README.md
          6. Upload   — all files pushed to S3 under {username}/{project_name}/

        Args:
            prompt:       Natural-language game description from the user.
            username:     S3 path prefix (owner of the project).
            project_name: S3 path prefix (project folder name).
            project_id:   Used for WebSocket broadcasts only.
            realtime:     Optional RealtimeManager for progress events.

        Returns:
            GodotGenerateResult with S3 URLs, stats, and any non-fatal errors.
        """
        result = GodotGenerateResult()
        errors: list[str] = []

        # ── Phase 1: Design ────────────────────────────────────────────────
        await _emit(realtime, project_id, "godot_progress", {"phase": "design", "status": "running"})
        design_result = await self.generate_design(prompt)
        design_doc = design_result.payload
        result.design_doc = design_doc

        entities_raw = design_doc.get("entities", ["player"])
        entities = [_normalize_entity(e) for e in entities_raw]
        if not any(e["type"] in ("character", "player") for e in entities):
            entities.insert(0, _normalize_entity("Player"))

        await _emit(realtime, project_id, "godot_progress", {"phase": "design", "status": "complete"})

        # ── Phase 2: Assets ────────────────────────────────────────────────
        await _emit(realtime, project_id, "godot_progress", {"phase": "assets", "status": "running"})
        asset_tasks = [asset_agent.run(e, design_doc) for e in entities]
        asset_results = await asyncio.gather(*asset_tasks, return_exceptions=True)

        sprite_map: dict[str, dict] = {}
        for i, res in enumerate(asset_results):
            ename = entities[i]["name"].lower().replace(" ", "_")
            if isinstance(res, Exception):
                errors.append(f"Asset failed for {ename}: {res}")
                sprite_map[ename] = {"png_b64": None}
            else:
                sprite_map[ename] = res

        tileset_b64 = await asset_agent.generate_tileset(design_doc)
        bg_b64 = await asset_agent.generate_background(design_doc)
        await _emit(realtime, project_id, "godot_progress", {"phase": "assets", "status": "complete"})

        # ── Phase 3: Scripts ───────────────────────────────────────────────
        await _emit(realtime, project_id, "godot_progress", {"phase": "scripts", "status": "running"})
        script_tasks = [script_agent.run(e, design_doc) for e in entities]
        script_results = await asyncio.gather(*script_tasks, return_exceptions=True)

        script_map: dict[str, str] = {}
        for i, res in enumerate(script_results):
            ename = entities[i]["name"].lower().replace(" ", "_")
            if isinstance(res, Exception):
                errors.append(f"Script failed for {ename}: {res}")
                script_map[ename] = _fallback_script(entities[i])
            else:
                script_map[ename] = res

        await _emit(realtime, project_id, "godot_progress", {"phase": "scripts", "status": "complete"})

        # ── Phase 4: Scenes ────────────────────────────────────────────────
        await _emit(realtime, project_id, "godot_progress", {"phase": "scenes", "status": "running"})
        scene_tasks = [scene_agent.run(e, design_doc) for e in entities]
        scene_results = await asyncio.gather(*scene_tasks, return_exceptions=True)

        scene_map: dict[str, str] = {}
        for i, res in enumerate(scene_results):
            ename = entities[i]["name"].lower().replace(" ", "_")
            if isinstance(res, Exception):
                errors.append(f"Scene failed for {ename}: {res}")
                scene_map[ename] = f'[gd_scene format=3]\n[node name="{ename}" type="Node2D"]\n'
            else:
                scene_map[ename] = res

        await _emit(realtime, project_id, "godot_progress", {"phase": "scenes", "status": "complete"})

        # ── Phase 5: Assembly ──────────────────────────────────────────────
        game_name = design_doc.get("game_type", "game").title() + " Game"
        project_config = _generate_project_config(game_name)
        main_scene = _generate_main_scene(entities)
        icon_svg = _generate_icon_svg()
        readme = _generate_readme(
            design_doc.get("game_type", "arcade"),
            design_doc.get("mechanics", []),
        )

        # ── Phase 6: Upload ────────────────────────────────────────────────
        await _emit(realtime, project_id, "godot_progress", {"phase": "upload", "status": "running"})
        file_urls: list[dict[str, str]] = []

        # Text files
        text_files = {
            "project.godot": project_config,
            "scenes/main.tscn": main_scene,
            "icon.svg": icon_svg,
            "README.md": readme,
        }
        for ename, content in scene_map.items():
            text_files[f"scenes/{ename}.tscn"] = content
        for ename, content in script_map.items():
            text_files[f"scripts/{ename}.gd"] = content

        for filename, content in text_files.items():
            try:
                r = await s3_storage.upload_file_content(username, project_name, filename, content)
                if r.get("url"):
                    file_urls.append({"filename": filename, "url": r["url"]})
            except Exception as e:
                errors.append(f"S3 upload failed for {filename}: {e}")
                logger.warning("S3 upload failed for %s: %s", filename, e)

        # Binary PNG assets
        for ename, asset_data in sprite_map.items():
            b64 = asset_data.get("png_b64")
            if not b64:
                continue
            try:
                raw_bytes = base64.b64decode(b64)
                r = await s3_storage.upload_bytes_content(
                    username, project_name, f"assets/{ename}.png", raw_bytes, "image/png"
                )
                if r.get("url"):
                    file_urls.append({"filename": f"assets/{ename}.png", "url": r["url"]})
            except Exception as e:
                errors.append(f"S3 PNG upload failed for {ename}: {e}")
                logger.warning("S3 PNG upload failed for %s: %s", ename, e)

        # Tileset and background
        for fname, b64 in [("assets/tileset.png", tileset_b64), ("assets/background.png", bg_b64)]:
            try:
                raw_bytes = base64.b64decode(b64)
                r = await s3_storage.upload_bytes_content(username, project_name, fname, raw_bytes, "image/png")
                if r.get("url"):
                    file_urls.append({"filename": fname, "url": r["url"]})
            except Exception as e:
                errors.append(f"S3 PNG upload failed for {fname}: {e}")

        result.file_urls = file_urls
        result.errors = errors
        result.stats = {
            "entities": len(entities),
            "scripts": len(script_map),
            "scenes": len(scene_map),
            "assets": len(sprite_map),
            "files_uploaded": len(file_urls),
        }
        result.status = "partial" if errors else "complete"

        await _emit(realtime, project_id, "godot_complete", {
            "status": result.status,
            "file_count": len(file_urls),
        })

        return result

    async def chat_reply(
        self,
        message: str,
        project: dict[str, Any],
        history: list[dict] | None = None,
    ) -> OrchestratorResult:
        system = "You are an expert game dev assistant. Respond concisely with practical next actions."
        lower = message.lower()
        project_name = project.get("name", "the project")

        if "optimiz" in lower:
            reply = (
                f"Optimization plan for {project_name}: reduce draw calls, pool enemies, "
                "and cap particle emitters during heavy scenes."
            )
            return OrchestratorResult(summary="reply", payload={"reply": reply}, usage=ProviderUsage())

        if any(k in lower for k in ("debug", "bug")):
            reply = (
                f"Debug checklist for {project_name}: verify collision layers, "
                "asset keys, and state transitions each frame."
            )
            return OrchestratorResult(summary="reply", payload={"reply": reply}, usage=ProviderUsage())

        history_text = self._format_history(history or [])
        full_prompt = f"{system}{history_text}\nCURRENT REQUEST: {message}"
        try:
            result = await provider_manager.generate(full_prompt, temperature=0.7)
            return OrchestratorResult(summary="reply", payload={"reply": result.text}, usage=result.usage)
        except Exception:
            reply = f'Assistant noted for {project_name}: "{message}". I can generate design/code updates or profiling guidance.'
            return OrchestratorResult(summary="reply", payload={"reply": reply}, usage=ProviderUsage())


ai_orchestrator = AIOrchestrator()
